Examples yaml :- 


# PV and PVC

apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
hostpath:
    path: /mnt/disks/ssd1

======================

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume
spec:
  storageClassName: "csi-hostpath-sc"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

=============================      

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: cache-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet #Change to "Deployment if required"
    name: cache-statefulset
  updatePolicy:
    updateMode: "Initial"
  resourcePolicy:
    containerPolicies:
      - containerName: cache-container
        controlledResources: ["cpu" , "memory"]
        maxAllowed:
          cpu: 1Gi
          memory: 500Mi
        minAllowed:
          cpu: 500Mi
          memory: 250Mi
        mode: "Auto"